apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - ${METALLB_POOL_ADDR}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: cluster
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
