---
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus-adapter
    chart: prometheus-community/prometheus-adapter
    version: 4.9.0
    namespace: prometheus
    installed: {{ env "PROMETHEUS_STACK_ENABLED" | default false }}
    values:
      - values/prometheus-adapter/common.yaml
