apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prd-cloudflare
  namespace: cert-manager
spec:
  acme:
    email: ${CF_API_EMAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prd-cloudflare-key
    solvers:
    - dns01:
        cloudflare:
          email: ${CF_API_EMAIL}
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key
