---
environments:
  default:
    values:
      - cni: {{ env "CUSTOM_CNI" | default "kind" }}
---
repositories:
{{ if eq .Environment.Values.cni "cilium" }}
  - name: cilium
    url: https://helm.cilium.io
{{ end }}
{{ if eq .Environment.Values.cni "calico" }}
  - name: projectcalico
    url: https://docs.tigera.io/calico/charts
{{ end }}
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns
  - name: jetstack
    url: https://charts.jetstack.io
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts


releases:
{{ if eq .Environment.Values.cni "cilium" }}
  - name: cilium
    chart: cilium/cilium
    version: 1.15.0
    namespace: cilium-system
    installed: true
    wait: true
    values:
      - ipam:
          mode: kubernetes
      - hubble:
          relay:
            enabled: true
          ui:
            enabled: true
{{ end }}

{{ if eq .Environment.Values.cni "calico" }}
  - name: projectcalico
    chart: projectcalico/tigera-operator
    version: v3.27.0
    namespace: tigera-operator
    installed: true
    wait: true
    disableValidationOnInstall: true
    values:
      - installation:
          cni:
            type: Calico
          calicoNetwork:
            bgp: Disabled
            ipPools:
            - cidr: 10.244.0.0/16
              encapsulation: VXLAN
    hooks:
      - events:
        - postsync
        showlogs: true
        command: "./scripts/calico/calico.sh"
{{ end }}

  - name: metrics-server
    chart: metrics-server/metrics-server
    version: 3.11.0
    namespace: kube-system
    installed: true
    values:
      - args:
          - --kubelet-insecure-tls

  - name: metallb
    chart: metallb/metallb
    version: 0.13.12
    namespace: metallb-system
    installed: true
    hooks:
      - events:
        - postsync
        showlogs: true
        command: "./scripts/metallb/metallb-config.sh"
        args:
          - {{ requiredEnv "METALLB_POOL_ADDR" }}

  - name: external-dns
    chart: external-dns/external-dns
    version: 1.14.3
    namespace: external-dns
    needs:
      - metallb-system/metallb
    values:
      - values/external-dns/values.yaml.gotmpl

  - name: cert-manager
    chart: jetstack/cert-manager
    version: 1.13.3
    namespace: cert-manager
    wait: true
    needs:
      - external-dns/external-dns
    installed: true
    values:
      - installCRDs: true
    hooks:
      - events:
        - postsync
        showlogs: true
        command: "./scripts/certmanager/certmanager-config.sh"
        args:
          - {{ requiredEnv "CLUSTER_NAME" }}
          - {{ requiredEnv "SITE_DOMAIN" }}
          - {{ requiredEnv "CF_API_EMAIL" }}

  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.9.1
    namespace: ingress-nginx
    installed: true
    wait: true
    needs:
      - cert-manager/cert-manager
    values:
      - values/ingress-nginx/values.yaml.gotmpl

  - name: prometheus
    chart: prometheus-community/kube-prometheus-stack
    version: 58.2.0
    namespace: prometheus
    installed: {{ env "PROMETHEUS_STACK_ENABLED" | default false }}
    needs:
      - ingress-nginx/ingress-nginx
    values:
      - cdrs:
          enabled: false
      - values/prometheus/values.yaml.gotmpl
    hooks:
      - events:
        - prepare
        showlogs: true
        command: "./scripts/prometheus/install-crds.sh"
